# .github/workflows/main.yml

name: Github Pages Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '1 0 * * *'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: sterlingwes/gh-pages-deploy-action@v1.1
        with:
          access-token: ${{ secrets.BUILD_PERSONAL_ACCESS_TOKEN }}
          source-directory: dist
          build-command: npm run generate
